//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DatPhong()
        {
            this.tb_DatPhong_SanPham = new HashSet<tb_DatPhong_SanPham>();
            this.tb_DATPHONG_CHITIET = new HashSet<tb_DATPHONG_CHITIET>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDKH { get; set; }
        public Nullable<int> IDPHONG { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public Nullable<int> SONGUOIO { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> IDSP { get; set; }
        public string MACTY { get; set; }
        public string MADVI { get; set; }
        public bool STATUS { get; set; }
        public bool DISABLED { get; set; }
        public bool THEODOAN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_BY { get; set; }
        public double SOTIEN { get; set; }
    
        public virtual tb_CongTy tb_CongTy { get; set; }
        public virtual tb_DonVi tb_DonVi { get; set; }
        public virtual tb_KhachHang tb_KhachHang { get; set; }
        public virtual tb_SanPham tb_SanPham { get; set; }
        public virtual tb_Users tb_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DatPhong_SanPham> tb_DatPhong_SanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DATPHONG_CHITIET> tb_DATPHONG_CHITIET { get; set; }
        public virtual tb_Phong tb_Phong { get; set; }
    }
}
